import LoginComponent from './login';
import MainScreenComponent from './mainscreen';
import ViewUserScreenComponent from './viewuserscreen';
import ViewFriendScreenComponent from './viewfriendscreen';
import DetailScreenTravis from './viewdetailscreenTravis';
import DetailScreenElon from './viewdetailscreenElon';
import DetailScreenEvan from './viewdetailscreenEvan';
import DetailScreenRichard from './viewdetailscreenRichard';
import DetailScreenPadma from './viewdetailscreenPadma';
import DetailScreenMeg from './viewdetailscreenMeg';
import DetailScreenJack from './viewdetailscreenJack';
import DetailScreenJackMa from './viewdetailscreenJackMa';
import DetailScreenMarissa from './viewdetailscreenMarissa';
import DetailScreenAlan from './viewdetailscreenAlan';
import DetailScreenKevin from './viewdetailscreenKevin';
import DetailScreenJohn from './viewdetailscreenJohn';


export const LoginView = LoginComponent;
export const MainScreenView = MainScreenComponent;
export const ViewUserView = ViewUserScreenComponent;
export const ViewFriendView = ViewFriendScreenComponent;
export const DetailScreenViewTravis = DetailScreenTravis;
export const DetailScreenViewElon = DetailScreenElon;
export const DetailScreenViewEvan = DetailScreenEvan;
export const DetailScreenViewRichard = DetailScreenRichard;
export const DetailScreenViewPadma = DetailScreenPadma;
export const DetailScreenViewMeg = DetailScreenMeg;
export const DetailScreenViewJack = DetailScreenJack;
export const DetailScreenViewJackMa = DetailScreenJackMa;
export const DetailScreenViewMarissa = DetailScreenMarissa;
export const DetailScreenViewAlan = DetailScreenAlan;
export const DetailScreenViewKevin = DetailScreenKevin;
export const DetailScreenViewJohn = DetailScreenJohn;
